apiVersion: v1
kind: Service
metadata:
  name: self-healing-k8s-demo
spec:
  type: LoadBalancer
  selector:
    app: self-healing-k8s-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
