apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: self-healing-k8s-demo
    spec:
      containers:
      - name: demo-http-server
        image: quay.io/robertjscott/demo-http-server:0.1.1
        livenessProbe:
          httpGet:
            path: /alive
            port: 3000
          periodSeconds: 5
          timeoutSeconds: 1
          initialDelaySeconds: 45
        env:
        - name: STARTUP_DELAY_SECONDS
          value: '40'
