apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mayhem-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: mayhem
    spec:
      containers:
      - name: mayhem
        image: quay.io/robertjscott/mayhem:0.1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "125m"
